import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { PageShell } from "@/components/PageShell";

export const metadata: Metadata = {
  title: "Pricing | What's Happening",
  description: "Public access costs $0. Account access and paid plans are not available today.",
  alternates: { canonical: "/pricing" },
};

const plans = [
  { name: "Public signal", price: "$0", note: "No account needed", description: "Browse the public signal views and open the source trail behind each record when production data is available.", features: ["World and trending views", "Country signal map", "Source-level evidence"], action: "Browse the feed", href: "/world", featured: false },
  { name: "Early access", price: "$0", note: "Account access unavailable", description: "Account identity and trend discussion are designed, but production account creation is not available yet.", features: ["Everything in Public signal", "Trend-specific developer chat when connected", "Saved identity when connected", "No published usage cap"], action: "Not available yet", href: null, featured: true },
  { name: "Teams", price: "—", note: "Not available", description: "There is no team plan, paid promise, or checkout today. We will publish real terms before offering one.", features: ["No payment collected", "No invented seat limits", "No hidden sales checkout"], action: "Not available yet", href: null, featured: false },
] as const;

export default function PricingPage() {
  return <PageShell><div className="mx-auto min-h-screen max-w-[1440px] px-5 pb-28 pt-32 sm:px-8 sm:pt-40">
    <header className="grid items-end gap-10 border-b border-white/[0.08] pb-12 lg:grid-cols-[1.2fr_0.8fr]"><div><p className="font-mono text-xs uppercase tracking-[0.22em] text-[#67E8F9]">Pricing / availability</p><h1 className="mt-5 max-w-5xl text-balance text-[clamp(3.5rem,9vw,8rem)] font-medium leading-[0.86] tracking-[-0.075em] text-white">Public access.<br />Still $0.</h1></div><p className="max-w-[35rem] text-pretty text-lg leading-8 text-[#A1A1AA] lg:pb-2">Public browsing costs $0. Account access and team plans are not available today. The cards below separate the working public surfaces from designed but unavailable features.</p></header>
    <section className="grid items-stretch gap-5 py-14 lg:grid-cols-3 lg:py-20" aria-label="Pricing plans">{plans.map((plan) => <article key={plan.name} className={`relative flex min-h-[560px] flex-col overflow-hidden rounded-[2rem] border p-7 sm:p-9 ${plan.featured ? "border-[#67E8F9]/45 bg-[#0D1113] lg:-translate-y-4" : "border-white/[0.08] bg-[#0B0B0D]"}`}>{plan.featured && <div className="absolute right-6 top-6 rounded-full border border-[#67E8F9]/25 bg-[#67E8F9]/10 px-3 py-1 font-mono text-[10px] uppercase tracking-[0.16em] text-[#67E8F9]">Unavailable</div>}<div><p className="text-sm font-medium text-[#B1B1B8]">{plan.name}</p><div className="mt-7 flex items-end gap-2"><span className="text-7xl font-medium tracking-[-0.07em] text-white">{plan.price}</span>{plan.price === "$0" && <span className="pb-2 text-xs uppercase tracking-wider text-[#777780]">USD</span>}</div><p className="mt-3 font-mono text-[10px] uppercase tracking-[0.16em] text-[#67E8F9]">{plan.note}</p><p className="mt-7 max-w-[42ch] text-sm leading-6 text-[#96969F]">{plan.description}</p></div><ul className="mt-9 space-y-4 border-t border-white/[0.08] pt-8">{plan.features.map((feature) => <li key={feature} className="flex items-start gap-3 text-sm leading-6 text-[#D4D4D8]"><span className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-[#67E8F9]/25 bg-[#67E8F9]/[0.07] text-[#67E8F9]"><Check size={12} /></span>{feature}</li>)}</ul><div className="mt-auto pt-10">{plan.href ? <Link href={plan.href} className={`flex min-h-12 w-full items-center justify-center gap-2 rounded-full text-sm font-semibold focus-visible:outline-2 focus-visible:outline-offset-3 focus-visible:outline-white ${plan.featured ? "bg-white text-black hover:bg-[#E8E8EA]" : "border border-white/15 text-white hover:bg-white/[0.06]"}`}>{plan.action}<ArrowRight size={16} /></Link> : <button type="button" disabled className="flex min-h-12 w-full cursor-not-allowed items-center justify-center rounded-full border border-white/[0.07] text-sm text-white/30">{plan.action}</button>}</div></article>)}</section>
    <section className="grid gap-6 border-t border-white/[0.08] pt-10 sm:grid-cols-3"><div><p className="font-mono text-xs uppercase tracking-widest text-white/35">Accounts</p><p className="mt-2 text-sm text-[#A1A1AA]">Creation and sign-in are unavailable.</p></div><div><p className="font-mono text-xs uppercase tracking-widest text-white/35">Usage</p><p className="mt-2 text-sm text-[#A1A1AA]">No published cap today.</p></div><div><p className="font-mono text-xs uppercase tracking-widest text-white/35">Billing</p><p className="mt-2 text-sm text-[#A1A1AA]">No checkout or paid plan exists.</p></div></section>
  </div></PageShell>;
}
