export type LocalizedText = { en: string; tr: string };

export type SecuritySource = {
  id: string;
  title: string;
  publisher: string;
  url: string;
  monitorUrl?: string;
};

export type MethodComparison = {
  name: LocalizedText;
  detects: LocalizedText;
  failureCondition: LocalizedText;
  operationalUse: LocalizedText;
};

export type SecurityDossier = {
  id: string;
  category: "Application" | "Data" | "Model" | "Agent" | "Hallucination";
  title: LocalizedText;
  summary: LocalizedText;
  riskModel: LocalizedText;
  prevention: LocalizedText;
  detection: LocalizedText;
  validation: LocalizedText;
  limitations: LocalizedText;
  workflow: LocalizedText;
  sourceIds: string[];
  methodComparison?: MethodComparison[];
};

export const securitySources: SecuritySource[] = [
  { id: "owasp-prompt", title: "LLM01:2025 Prompt Injection", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/" },
  { id: "owasp-disclosure", title: "LLM02:2025 Sensitive Information Disclosure", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm022025-sensitive-information-disclosure/" },
  { id: "owasp-supply", title: "LLM03:2025 Supply Chain", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm032025-supply-chain/" },
  { id: "owasp-poison", title: "LLM04:2025 Data and Model Poisoning", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm042025-data-and-model-poisoning/" },
  { id: "owasp-output", title: "LLM05:2025 Improper Output Handling", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm052025-improper-output-handling/" },
  { id: "owasp-agency", title: "LLM06:2025 Excessive Agency", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm062025-excessive-agency/" },
  { id: "owasp-prompt-leak", title: "LLM07:2025 System Prompt Leakage", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm072025-system-prompt-leakage/" },
  { id: "owasp-vector", title: "LLM08:2025 Vector and Embedding Weaknesses", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm082025-vector-and-embedding-weaknesses/" },
  { id: "owasp-misinformation", title: "LLM09:2025 Misinformation", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm092025-misinformation/" },
  { id: "owasp-consumption", title: "LLM10:2025 Unbounded Consumption", publisher: "OWASP Gen AI Security Project", url: "https://genai.owasp.org/llmrisk/llm102025-unbounded-consumption/" },
  { id: "nist-aml", title: "Adversarial Machine Learning: A Taxonomy and Terminology of Attacks and Mitigations", publisher: "NIST", url: "https://csrc.nist.gov/pubs/ai/100/2/e2025/final" },
  { id: "nist-genai", title: "Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile", publisher: "NIST", url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf" },
  { id: "mitre-atlas", title: "MITRE ATLAS", publisher: "MITRE", url: "https://atlas.mitre.org/" },
  { id: "cisa-deploy", title: "Joint Guidance on Deploying AI Systems Securely", publisher: "CISA, NSA and international partners", url: "https://www.cisa.gov/news-events/alerts/2024/04/15/joint-guidance-deploying-ai-systems-securely" },
  { id: "rag-paper", title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks", publisher: "Primary research", url: "https://arxiv.org/abs/2005.11401" },
  { id: "selfcheckgpt", title: "SelfCheckGPT: Zero-Resource Black-Box Hallucination Detection for Generative Large Language Models", publisher: "Primary research", url: "https://arxiv.org/abs/2303.08896" },
  { id: "truthfulqa", title: "TruthfulQA: Measuring How Models Mimic Human Falsehoods", publisher: "Primary research", url: "https://arxiv.org/abs/2109.07958" },
  { id: "factscore", title: "FActScore: Fine-grained Atomic Evaluation of Factual Precision in Long Form Text Generation", publisher: "Primary research", url: "https://arxiv.org/abs/2305.14251" },
  {
    id: "semantic-entropy",
    title: "Detecting hallucinations in large language models using semantic entropy",
    publisher: "Nature",
    url: "https://www.nature.com/articles/s41586-024-07421-0",
    monitorUrl: "https://arxiv.org/abs/2302.09664",
  },
  { id: "halueval", title: "HaluEval: A Large-Scale Hallucination Evaluation Benchmark for Large Language Models", publisher: "ACL Anthology", url: "https://aclanthology.org/2023.emnlp-main.397/" },
  { id: "model-stealing", title: "Stealing Machine Learning Models via Prediction APIs", publisher: "USENIX Security", url: "https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/tramer" },
  { id: "membership-inference", title: "Membership Inference Attacks Against Machine Learning Models", publisher: "IEEE Symposium on Security and Privacy", url: "https://www.cs.cornell.edu/~shmat/shmat_oak17.pdf" },
];

const hallucinationMethods: MethodComparison[] = [
  {
    name: { en: "Retrieval grounding", tr: "Bilgi getirme ile dayanaklandırma" },
    detects: { en: "Checks whether a claim is supported by retrieved, approved evidence.", tr: "Bir iddianın getirilen ve onaylı kanıtla desteklenip desteklenmediğini kontrol eder." },
    failureCondition: { en: "Fails when retrieval misses the right evidence, the corpus is stale or poisoned, or support is only superficial.", tr: "Doğru kanıt getirilemediğinde, külliyat eski ya da zehirli olduğunda veya destek yalnızca yüzeysel olduğunda başarısız olur." },
    operationalUse: { en: "Require passage-level citations and reject answers with no attributable support.", tr: "Paragraf düzeyinde kaynak isteyin ve atfedilebilir desteği olmayan yanıtları reddedin." },
  },
  {
    name: { en: "Atomic claim verification", tr: "Atomik iddia doğrulama" },
    detects: { en: "Splits long output into testable facts and scores each fact against evidence.", tr: "Uzun çıktıyı test edilebilir olgulara ayırır ve her olguyu kanıta göre puanlar." },
    failureCondition: { en: "Misses errors when claims are decomposed badly, evidence is ambiguous, or the verifier shares the generator's bias.", tr: "İddialar kötü ayrıştırıldığında, kanıt belirsiz olduğunda veya doğrulayıcı üreticiyle aynı yanlılığı taşıdığında hataları kaçırır." },
    operationalUse: { en: "Use for long-form reports and route unsupported high-impact claims to review.", tr: "Uzun raporlarda kullanın ve desteklenmeyen yüksek etkili iddiaları incelemeye yönlendirin." },
  },
  {
    name: { en: "NLI entailment checking", tr: "NLI çıkarım denetimi" },
    detects: { en: "Classifies a claim as entailed, contradicted or not established by a cited passage.", tr: "Bir iddiayı kaynak paragraf tarafından desteklenen, çelişen ya da belirlenemeyen olarak sınıflandırır." },
    failureCondition: { en: "Struggles with numerical reasoning, temporal qualifiers, long context and domains unlike its training data.", tr: "Sayısal akıl yürütme, zaman niteleyicileri, uzun bağlam ve eğitim verisinden farklı alanlarda zorlanır." },
    operationalUse: { en: "Treat undecidable results as a review state, not as support.", tr: "Karar verilemeyen sonuçları destek değil, inceleme durumu olarak ele alın." },
  },
  {
    name: { en: "Self-consistency sampling", tr: "Öz tutarlılık örneklemesi" },
    detects: { en: "Flags statements that change across independently sampled answers.", tr: "Bağımsız örneklenen yanıtlar arasında değişen ifadeleri işaretler." },
    failureCondition: { en: "Consistently repeated misconceptions look stable, and sampling increases cost and latency.", tr: "Sürekli tekrarlanan yanlış inanışlar kararlı görünür; örnekleme maliyet ve gecikmeyi artırır." },
    operationalUse: { en: "Use as a risk signal alongside evidence checks, never as a truth oracle.", tr: "Kanıt denetimleriyle birlikte risk sinyali olarak kullanın, doğruluk ölçütü olarak değil." },
  },
  {
    name: { en: "Semantic entropy", tr: "Anlamsal entropi" },
    detects: { en: "Groups sampled answers by meaning and estimates uncertainty over those meanings.", tr: "Örneklenen yanıtları anlama göre gruplar ve anlamlar üzerindeki belirsizliği tahmin eder." },
    failureCondition: { en: "Targets confabulation, not consistently wrong answers; meaning clustering can also introduce errors.", tr: "Tutarlı biçimde yanlış yanıtları değil, uydurmaları hedefler; anlam kümeleme de hata üretebilir." },
    operationalUse: { en: "Escalate high-entropy questions to retrieval, refusal or human review.", tr: "Yüksek entropili soruları bilgi getirme, yanıt vermeme veya insan incelemesine yükseltin." },
  },
  {
    name: { en: "Human review with calibrated abstention", tr: "Kalibre edilmiş kaçınma ile insan incelemesi" },
    detects: { en: "Uses accountable subject-matter review when automated signals exceed a risk threshold.", tr: "Otomatik sinyaller risk eşiğini aştığında sorumlu alan uzmanı incelemesini kullanır." },
    failureCondition: { en: "Reviewers can be overloaded, anchored by fluent text, or lack access to authoritative evidence.", tr: "İnceleyenler aşırı yüklenebilir, akıcı metne bağlanabilir veya yetkili kanıta erişemeyebilir." },
    operationalUse: { en: "Define ownership, evidence requirements and stop conditions before deployment.", tr: "Dağıtımdan önce sorumluluğu, kanıt gereksinimlerini ve durma koşullarını tanımlayın." },
  },
];

export const securityDossiers: SecurityDossier[] = [
  {
    id: "prompt-injection",
    category: "Application",
    title: { en: "Prompt injection containment", tr: "Prompt enjeksiyonunu sınırlama" },
    summary: { en: "Keep model instructions from becoming an authorization boundary.", tr: "Model talimatlarının bir yetkilendirme sınırına dönüşmesini önleyin." },
    riskModel: { en: "Untrusted user content competes with application instructions and can redirect the model toward unauthorized disclosure or actions.", tr: "Güvenilmeyen kullanıcı içeriği uygulama talimatlarıyla yarışarak modeli yetkisiz açıklama veya eylemlere yöneltebilir." },
    prevention: { en: "Separate instructions from data, enforce permissions in deterministic code, minimize connected capabilities and require approval for consequential actions.", tr: "Talimatları veriden ayırın, izinleri deterministik kodda uygulayın, bağlı yetenekleri azaltın ve önemli eylemlerde onay isteyin." },
    detection: { en: "Log instruction conflicts, tool requests, denied operations and policy-filter outcomes without retaining sensitive prompt bodies.", tr: "Hassas prompt gövdelerini saklamadan talimat çatışmalarını, araç isteklerini, reddedilen işlemleri ve politika filtresi sonuçlarını kaydedin." },
    validation: { en: "Run direct, multilingual and obfuscated adversarial cases against every privileged path and assert that server-side policy still denies access.", tr: "Her ayrıcalıklı yolda doğrudan, çok dilli ve gizlenmiş karşıt örnekler çalıştırın; sunucu tarafı politikanın erişimi hâlâ reddettiğini doğrulayın." },
    limitations: { en: "Input filtering and system prompts reduce exposure but do not reliably eliminate prompt injection.", tr: "Girdi filtreleme ve sistem promptları maruziyeti azaltır ancak prompt enjeksiyonunu güvenilir biçimde ortadan kaldırmaz." },
    workflow: { en: "Treat the model as an untrusted planner: validate its proposed action against user identity, resource scope and an explicit allowlist before execution.", tr: "Modeli güvenilmeyen bir planlayıcı sayın: önerdiği eylemi çalıştırmadan önce kullanıcı kimliği, kaynak kapsamı ve açık izin listesine göre doğrulayın." },
    sourceIds: ["owasp-prompt", "nist-aml", "mitre-atlas"],
  },
  {
    id: "indirect-prompt-injection",
    category: "Application",
    title: { en: "Indirect prompt injection in retrieved content", tr: "Getirilen içerikte dolaylı prompt enjeksiyonu" },
    summary: { en: "Assume documents, pages, messages and images can carry hostile instructions.", tr: "Belge, sayfa, mesaj ve görsellerin zararlı talimat taşıyabileceğini varsayın." },
    riskModel: { en: "An attacker plants instructions in content the system later retrieves, causing the model to treat external data as control text.", tr: "Saldırgan, sistemin daha sonra getireceği içeriğe talimat yerleştirir; model dış veriyi kontrol metni gibi yorumlar." },
    prevention: { en: "Preserve source trust labels, isolate retrieved text, strip active content, narrow tools and block retrieved content from changing policy or recipients.", tr: "Kaynak güven etiketlerini koruyun, getirilen metni yalıtın, etkin içeriği temizleyin, araçları daraltın ve getirilen içeriğin politika ya da alıcı değiştirmesini engelleyin." },
    detection: { en: "Flag instruction-like phrases in external context, unusual tool transitions and source-to-action chains that cross trust zones.", tr: "Dış bağlamdaki talimat benzeri ifadeleri, olağandışı araç geçişlerini ve güven bölgelerini aşan kaynak-eylem zincirlerini işaretleyin." },
    validation: { en: "Seed defensive test documents across every ingestion format and confirm they cannot change tool parameters, destinations or secrets access.", tr: "Her alım biçimine savunma test belgeleri yerleştirin; bunların araç parametrelerini, hedefleri veya gizli bilgi erişimini değiştiremediğini doğrulayın." },
    limitations: { en: "Content classifiers miss novel encodings and multimodal instructions, so containment must survive detection failure.", tr: "İçerik sınıflandırıcıları yeni kodlamaları ve çok modlu talimatları kaçırır; bu nedenle sınırlama tespit hatasına dayanmalıdır." },
    workflow: { en: "Fetch into a low-trust zone, sanitize and label, retrieve only the needed excerpt, then authorize any resulting action outside the model.", tr: "İçeriği düşük güvenli bölgeye alın, temizleyip etiketleyin, yalnız gerekli bölümü getirin ve ortaya çıkan her eylemi model dışında yetkilendirin." },
    sourceIds: ["owasp-prompt", "owasp-vector", "mitre-atlas"],
  },
  {
    id: "sensitive-information-disclosure",
    category: "Application",
    title: { en: "Sensitive information disclosure", tr: "Hassas bilgi ifşası" },
    summary: { en: "Control what enters context and what is allowed to leave it.", tr: "Bağlama neyin girdiğini ve bağlamdan neyin çıkabildiğini kontrol edin." },
    riskModel: { en: "Prompts, retrieval results, tool output, logs or model training data can expose personal data, credentials or confidential business information.", tr: "Promptlar, getirilen sonuçlar, araç çıktısı, günlükler veya model eğitim verisi kişisel verileri, kimlik bilgilerini ya da gizli iş bilgisini açığa çıkarabilir." },
    prevention: { en: "Classify data, redact before inference, use scoped retrieval, keep secrets out of prompts and apply output data-loss controls.", tr: "Veriyi sınıflandırın, çıkarımdan önce maskeleyin, kapsamlı bilgi getirme kullanın, sırları promptlardan uzak tutun ve çıktı veri kaybı kontrolleri uygulayın." },
    detection: { en: "Scan outputs for secret formats and protected entities, monitor unusual retrieval breadth and alert on repeated boundary probes.", tr: "Çıktılarda gizli bilgi biçimlerini ve korunan varlıkları tarayın, olağandışı geniş bilgi getirmeyi izleyin ve tekrarlanan sınır yoklamalarında uyarı verin." },
    validation: { en: "Use synthetic canary secrets in each data zone and verify they never appear outside the authorized response path or logs.", tr: "Her veri bölgesinde sentetik kanarya sırları kullanın; bunların yetkili yanıt yolu veya günlükler dışında görünmediğini doğrulayın." },
    limitations: { en: "Pattern matching misses transformed or semantically inferred secrets and can over-block legitimate content.", tr: "Desen eşleme dönüştürülmüş veya anlamsal olarak çıkarılmış sırları kaçırabilir ve meşru içeriği fazla engelleyebilir." },
    workflow: { en: "Authorize retrieval per record, minimize the returned fields, redact context, generate, scan the response, then release or quarantine it.", tr: "Bilgi getirmeyi kayıt başına yetkilendirin, dönen alanları azaltın, bağlamı maskeleyin, yanıtı üretip tarayın ve sonra yayınlayın ya da karantinaya alın." },
    sourceIds: ["owasp-disclosure", "nist-genai", "cisa-deploy"],
  },
  {
    id: "model-supply-chain",
    category: "Model",
    title: { en: "Model and dependency supply chain", tr: "Model ve bağımlılık tedarik zinciri" },
    summary: { en: "Make every model, adapter, dataset and runtime artifact traceable.", tr: "Her model, adaptör, veri seti ve çalışma zamanı öğesini izlenebilir kılın." },
    riskModel: { en: "Compromised repositories, unsafe serialization, mutable tags or opaque providers can introduce malicious code, backdoors or unexpected behavior.", tr: "Ele geçirilmiş depolar, güvensiz serileştirme, değişken etiketler veya şeffaf olmayan sağlayıcılar zararlı kod, arka kapı ya da beklenmedik davranış ekleyebilir." },
    prevention: { en: "Pin immutable versions, verify signatures and hashes, prefer safe formats, inventory provenance and sandbox untrusted artifacts before promotion.", tr: "Değişmez sürümleri sabitleyin, imza ve karmaları doğrulayın, güvenli biçimleri tercih edin, kaynağı envantere alın ve güvenilmeyen öğeleri yükseltmeden önce yalıtın." },
    detection: { en: "Monitor checksum drift, dependency advisories, unexpected files, capability changes and deviations from a signed release manifest.", tr: "Karma değişimini, bağımlılık duyurularını, beklenmedik dosyaları, yetenek değişimlerini ve imzalı sürüm manifestinden sapmaları izleyin." },
    validation: { en: "Reproduce the build, scan artifacts, compare behavior to a trusted baseline and rehearse rollback before production admission.", tr: "Derlemeyi yeniden üretin, öğeleri tarayın, davranışı güvenilir temel çizgiyle karşılaştırın ve üretime kabulden önce geri dönüşü prova edin." },
    limitations: { en: "A clean signature proves artifact identity, not that the model is safe or that its training data is trustworthy.", tr: "Temiz bir imza öğenin kimliğini kanıtlar; modelin güvenli veya eğitim verisinin güvenilir olduğunu kanıtlamaz." },
    workflow: { en: "Acquire into quarantine, verify provenance and integrity, run security and behavior gates, sign the approved bundle and deploy by digest.", tr: "Öğeyi karantinaya alın, kaynak ve bütünlüğü doğrulayın, güvenlik ve davranış kapılarını çalıştırın, onaylı paketi imzalayın ve özet değerle dağıtın." },
    sourceIds: ["owasp-supply", "cisa-deploy", "nist-aml"],
  },
  {
    id: "training-data-poisoning",
    category: "Data",
    title: { en: "Training and fine-tuning data poisoning", tr: "Eğitim ve ince ayar verisi zehirleme" },
    summary: { en: "Protect the data path that changes model behavior.", tr: "Model davranışını değiştiren veri yolunu koruyun." },
    riskModel: { en: "An attacker alters a small but influential subset of training or feedback data to create targeted errors, bias or hidden triggers.", tr: "Saldırgan, hedefli hata, yanlılık veya gizli tetikleyici üretmek için eğitim ya da geri bildirim verisinin küçük fakat etkili bir bölümünü değiştirir." },
    prevention: { en: "Track lineage, restrict write access, separate contributors, deduplicate data, review high-influence samples and preserve immutable snapshots.", tr: "Veri kökenini izleyin, yazma erişimini kısıtlayın, katkı sahiplerini ayırın, tekrarları temizleyin, yüksek etkili örnekleri inceleyin ve değişmez anlık görüntüler saklayın." },
    detection: { en: "Look for source concentration, label anomalies, trigger-linked behavior, distribution shifts and training runs that diverge from controls.", tr: "Kaynak yoğunlaşmasını, etiket anomalilerini, tetikleyici bağlantılı davranışı, dağılım kaymalarını ve kontrol koşullarından sapan eğitim çalıştırmalarını arayın." },
    validation: { en: "Compare clean-room and candidate models on held-out slices, influence-focused tests and known trigger families before release.", tr: "Yayın öncesinde temiz ortam ve aday modelleri ayrılmış veri dilimleri, etki odaklı testler ve bilinen tetikleyici ailelerinde karşılaştırın." },
    limitations: { en: "Poisoning can mimic normal long-tail data, and no single statistical test establishes that a corpus is clean.", tr: "Zehirleme normal uzun kuyruk verisini taklit edebilir; tek bir istatistiksel test bir külliyatın temiz olduğunu kanıtlamaz." },
    workflow: { en: "Ingest with provenance, quarantine anomalies, train reproducibly, compare against a signed baseline and require two-person approval for promotion.", tr: "Veriyi kökeniyle alın, anomalileri karantinaya alın, yeniden üretilebilir biçimde eğitin, imzalı temel çizgiyle karşılaştırın ve yükseltme için iki kişi onayı isteyin." },
    sourceIds: ["owasp-poison", "nist-aml", "mitre-atlas"],
  },
  {
    id: "rag-vector-poisoning",
    category: "Data",
    title: { en: "RAG and vector-store poisoning", tr: "RAG ve vektör deposu zehirleme" },
    summary: { en: "A relevant passage is not automatically a trustworthy passage.", tr: "İlgili bir paragraf otomatik olarak güvenilir değildir." },
    riskModel: { en: "Malicious or low-quality documents can rank highly in retrieval, steer answers, cross tenant boundaries or carry indirect instructions.", tr: "Zararlı ya da düşük kaliteli belgeler bilgi getirmede üst sıraya çıkabilir, yanıtları yönlendirebilir, kiracı sınırlarını aşabilir veya dolaylı talimat taşıyabilir." },
    prevention: { en: "Enforce tenant filters before similarity search, retain provenance, approve sources, limit write paths and separate instructions from retrieved evidence.", tr: "Benzerlik aramasından önce kiracı filtrelerini uygulayın, kökeni koruyun, kaynakları onaylayın, yazma yollarını sınırlayın ve talimatları getirilen kanıttan ayırın." },
    detection: { en: "Monitor sudden rank changes, duplicate clusters, source reputation, retrieval diversity and documents that produce disproportionate answer influence.", tr: "Ani sıralama değişimlerini, tekrar kümelerini, kaynak itibarını, getirme çeşitliliğini ve yanıt üzerinde orantısız etkisi olan belgeleri izleyin." },
    validation: { en: "Test cross-tenant isolation, poisoned-corpus scenarios, citation alignment and removal propagation from index to response.", tr: "Kiracılar arası yalıtımı, zehirli külliyat senaryolarını, kaynak uyumunu ve silmenin dizinden yanıta yayılmasını test edin." },
    limitations: { en: "Embedding distance measures semantic similarity, not truth, authority or instruction safety.", tr: "Gömme uzaklığı anlamsal benzerliği ölçer; doğruluğu, yetkiyi veya talimat güvenliğini ölçmez." },
    workflow: { en: "Authorize and label documents at ingestion, retrieve within policy, rerank for authority, scan context, answer with citations and support deletion.", tr: "Belgeleri alımda yetkilendirip etiketleyin, politika içinde getirin, yetkiye göre yeniden sıralayın, bağlamı tarayın, kaynaklı yanıt verin ve silmeyi destekleyin." },
    sourceIds: ["owasp-vector", "owasp-poison", "rag-paper"],
  },
  {
    id: "improper-output-handling",
    category: "Application",
    title: { en: "Improper model-output handling", tr: "Model çıktısını güvensiz işleme" },
    summary: { en: "Treat generated output as untrusted input to every downstream system.", tr: "Üretilen çıktıyı her alt sistem için güvenilmeyen girdi sayın." },
    riskModel: { en: "Generated markup, code, queries or tool arguments can trigger injection, unsafe rendering or unauthorized execution when consumed directly.", tr: "Üretilen işaretleme, kod, sorgu veya araç argümanları doğrudan kullanıldığında enjeksiyon, güvensiz gösterim ya da yetkisiz çalıştırma tetikleyebilir." },
    prevention: { en: "Use typed schemas, escaping, parameterized interfaces, allowlists and sandboxing; never execute raw model text.", tr: "Türlü şemalar, kaçışlama, parametreli arayüzler, izin listeleri ve yalıtım kullanın; ham model metnini asla çalıştırmayın." },
    detection: { en: "Record parser failures, rejected fields, dangerous sink attempts and mismatches between requested and generated operations.", tr: "Ayrıştırıcı hatalarını, reddedilen alanları, tehlikeli hedef girişimlerini ve istenen ile üretilen işlemler arasındaki uyumsuzluğu kaydedin." },
    validation: { en: "Fuzz every output-to-sink adapter with malformed structures and verify encoding at the final rendering or execution boundary.", tr: "Her çıktı-hedef adaptörünü bozuk yapılarla test edin ve son gösterim ya da çalıştırma sınırında kodlamayı doğrulayın." },
    limitations: { en: "Schema validity does not establish business authorization or semantic safety.", tr: "Şema geçerliliği iş yetkilendirmesini veya anlamsal güvenliği kanıtlamaz." },
    workflow: { en: "Generate a typed proposal, parse strictly, authorize values, preview high-impact changes, execute through a narrow adapter and audit the result.", tr: "Türlü bir öneri üretin, katı ayrıştırın, değerleri yetkilendirin, yüksek etkili değişiklikleri önizleyin, dar bir adaptörle çalıştırın ve sonucu denetleyin." },
    sourceIds: ["owasp-output", "owasp-agency", "cisa-deploy"],
  },
  {
    id: "excessive-agency",
    category: "Agent",
    title: { en: "Excessive agency and tool privilege", tr: "Aşırı özerklik ve araç yetkisi" },
    summary: { en: "Reduce what an agent can do, not only what it is told to do.", tr: "Bir ajanın yalnızca ne söylendiğini değil, ne yapabildiğini de azaltın." },
    riskModel: { en: "An agent with unnecessary functions, broad credentials or unchecked autonomy can turn model error or manipulation into real-world impact.", tr: "Gereksiz işlevlere, geniş kimlik bilgilerine veya denetimsiz özerkliğe sahip bir ajan, model hatasını ya da manipülasyonunu gerçek dünya etkisine dönüştürebilir." },
    prevention: { en: "Give each task a scoped identity, narrow function set, bounded resources and explicit approval for irreversible or external actions.", tr: "Her göreve kapsamlı kimlik, dar işlev kümesi, sınırlı kaynak ve geri döndürülemez ya da dış eylemler için açık onay verin." },
    detection: { en: "Alert on new tool sequences, privilege denials, repeated retries, destination changes and actions outside the user's active intent.", tr: "Yeni araç dizilerinde, yetki reddinde, tekrarlanan denemelerde, hedef değişikliklerinde ve kullanıcının etkin niyeti dışındaki eylemlerde uyarı verin." },
    validation: { en: "Run scenario tests for compromised tools, hallucinated parameters and malicious context while checking that policy blocks the final action.", tr: "Ele geçirilmiş araçlar, uydurulmuş parametreler ve zararlı bağlam senaryoları çalıştırırken politikanın son eylemi engellediğini kontrol edin." },
    limitations: { en: "Human approval can become a rubber stamp if reviewers lack context or receive too many prompts.", tr: "İnceleyenler bağlamdan yoksunsa veya çok fazla onay isteği alıyorsa insan onayı göstermelik hale gelebilir." },
    workflow: { en: "Plan in read-only mode, resolve exact resources, display the proposed effect, obtain risk-based approval and execute with a short-lived credential.", tr: "Salt okunur modda planlayın, kesin kaynakları çözün, önerilen etkiyi gösterin, riske dayalı onay alın ve kısa ömürlü kimlik bilgisiyle çalıştırın." },
    sourceIds: ["owasp-agency", "nist-aml", "mitre-atlas"],
  },
  {
    id: "system-prompt-secrets",
    category: "Application",
    title: { en: "System prompts, secrets and trust boundaries", tr: "Sistem promptları, sırlar ve güven sınırları" },
    summary: { en: "A hidden prompt is configuration, not a secret vault or policy engine.", tr: "Gizli prompt yapılandırmadır; sır kasası veya politika motoru değildir." },
    riskModel: { en: "System instructions may be reconstructed or exposed, revealing confidential data or controls that fail once known.", tr: "Sistem talimatları yeniden oluşturulabilir veya açığa çıkabilir; gizli veriyi ya da bilindiğinde başarısız olan kontrolleri gösterebilir." },
    prevention: { en: "Keep credentials and sensitive business data outside prompts, enforce controls in code and design instructions to remain safe if disclosed.", tr: "Kimlik bilgilerini ve hassas iş verisini promptların dışında tutun, kontrolleri kodda uygulayın ve talimatları açığa çıksa da güvenli kalacak biçimde tasarlayın." },
    detection: { en: "Use canary markers, scan responses for protected configuration fragments and investigate repeated extraction-style conversations.", tr: "Kanarya işaretleri kullanın, yanıtlarda korunan yapılandırma parçalarını tarayın ve tekrarlanan çıkarma tarzı konuşmaları inceleyin." },
    validation: { en: "Assume the full prompt is public during threat modeling and verify that no data access or authorization decision changes.", tr: "Tehdit modellemede tam promptun açık olduğunu varsayın; hiçbir veri erişimi veya yetkilendirme kararının değişmediğini doğrulayın." },
    limitations: { en: "Refusal instructions can reduce accidental disclosure but cannot guarantee prompt confidentiality.", tr: "Reddetme talimatları kazara ifşayı azaltabilir ancak prompt gizliliğini garanti edemez." },
    workflow: { en: "Store secrets in a vault, pass only scoped results, inspect output for leaks and rotate any credential that crosses the model boundary.", tr: "Sırları kasada tutun, yalnız kapsamlı sonuçları aktarın, çıktıda sızıntı tarayın ve model sınırını geçen her kimlik bilgisini döndürün." },
    sourceIds: ["owasp-prompt-leak", "owasp-disclosure", "nist-genai"],
  },
  {
    id: "jailbreak-resilience",
    category: "Model",
    title: { en: "Jailbreak resilience testing", tr: "Jailbreak dayanıklılık testi" },
    summary: { en: "Measure policy bypass as a changing failure surface, not a solved filter.", tr: "Politika aşımını çözülmüş bir filtre değil, değişen bir hata yüzeyi olarak ölçün." },
    riskModel: { en: "Adversarial phrasing, encoding, role-play or multimodal inputs can elicit behavior the deployment policy intends to block.", tr: "Karşıt ifade, kodlama, rol yapma veya çok modlu girdiler dağıtım politikasının engellemek istediği davranışı ortaya çıkarabilir." },
    prevention: { en: "Layer model alignment with input controls, output checks, least privilege and use-case-specific refusal and escalation rules.", tr: "Model hizalamasını girdi kontrolleri, çıktı denetimleri, en az yetki ve kullanım alanına özel reddetme ile yükseltme kurallarıyla katmanlayın." },
    detection: { en: "Track policy-category failures, repeated reformulations, encoding changes and drift by model and prompt version.", tr: "Politika kategorisi hatalarını, tekrarlanan yeniden ifadeleri, kodlama değişimlerini ve model ile prompt sürümüne göre kaymayı izleyin." },
    validation: { en: "Maintain a defensive red-team suite with benign controls, measure both bypass and over-refusal, and rerun after every model change.", tr: "Zararsız kontroller içeren savunma kırmızı takım paketi tutun, hem aşımı hem aşırı reddi ölçün ve her model değişiminden sonra yeniden çalıştırın." },
    limitations: { en: "Passing a fixed jailbreak set does not establish resilience to adaptive or unseen attacks.", tr: "Sabit bir jailbreak setini geçmek uyarlanabilir veya görülmemiş saldırılara dayanıklılığı kanıtlamaz." },
    workflow: { en: "Define policy, generate safe adversarial transformations, test in isolation, triage failures, add regression cases and gate release on risk thresholds.", tr: "Politikayı tanımlayın, güvenli karşıt dönüşümler üretin, yalıtılmış ortamda test edin, hataları ayırın, regresyon örnekleri ekleyin ve sürümü risk eşiklerine bağlayın." },
    sourceIds: ["owasp-prompt", "nist-aml", "nist-genai"],
  },
  {
    id: "unbounded-consumption",
    category: "Application",
    title: { en: "Unbounded consumption and denial of service", tr: "Sınırsız tüketim ve hizmet engelleme" },
    summary: { en: "Bound tokens, tools, time and spend at every level.", tr: "Token, araç, süre ve harcamayı her düzeyde sınırlayın." },
    riskModel: { en: "Long contexts, recursive agents, repeated tool calls or many parallel requests can exhaust compute, quota or budget.", tr: "Uzun bağlamlar, özyinelemeli ajanlar, tekrarlanan araç çağrıları veya çok sayıda paralel istek işlem, kota ya da bütçeyi tüketebilir." },
    prevention: { en: "Apply per-user and global quotas, token and step budgets, timeouts, concurrency caps, caching and circuit breakers.", tr: "Kullanıcı başına ve küresel kota, token ile adım bütçesi, zaman aşımı, eşzamanlılık sınırı, önbellek ve devre kesici uygulayın." },
    detection: { en: "Monitor cost per task, recursion depth, repeated near-identical calls, queue saturation and abnormal completion lengths.", tr: "Görev başına maliyeti, özyineleme derinliğini, tekrarlanan benzer çağrıları, kuyruk doygunluğunu ve olağandışı tamamlama uzunluklarını izleyin." },
    validation: { en: "Load-test worst-case contexts and tool loops, then confirm graceful cancellation and bounded financial exposure.", tr: "En kötü bağlamları ve araç döngülerini yük testine sokun; düzgün iptali ve sınırlı mali maruziyeti doğrulayın." },
    limitations: { en: "Hard limits protect capacity but can interrupt legitimate long-running work and require product-specific tuning.", tr: "Sert sınırlar kapasiteyi korur ancak meşru uzun işleri kesebilir ve ürüne özel ayar gerektirir." },
    workflow: { en: "Estimate a task budget, reserve capacity, meter each step, stop at thresholds and return a resumable partial result instead of retrying blindly.", tr: "Görev bütçesini tahmin edin, kapasite ayırın, her adımı ölçün, eşiklerde durun ve körlemesine yeniden denemek yerine sürdürülebilir kısmi sonuç döndürün." },
    sourceIds: ["owasp-consumption", "owasp-agency", "cisa-deploy"],
  },
  {
    id: "model-extraction",
    category: "Model",
    title: { en: "Model extraction and replication", tr: "Model çıkarma ve kopyalama" },
    summary: { en: "Detect systematic querying that reconstructs behavior or parameters.", tr: "Davranışı veya parametreleri yeniden kuran sistematik sorgulamayı tespit edin." },
    riskModel: { en: "An attacker uses repeated API queries to approximate a model, infer decision boundaries or copy proprietary behavior.", tr: "Saldırgan, modeli yaklaşık olarak kopyalamak, karar sınırlarını çıkarmak veya özel davranışı çoğaltmak için tekrarlanan API sorguları kullanır." },
    prevention: { en: "Use authentication, scoped quotas, output minimization, abuse controls and contractual boundaries appropriate to model value.", tr: "Model değerine uygun kimlik doğrulama, kapsamlı kota, çıktı azaltma, kötüye kullanım kontrolleri ve sözleşme sınırları kullanın." },
    detection: { en: "Look for broad coverage queries, synthetic grids, high-volume low-value sessions and coordinated accounts with shared patterns.", tr: "Geniş kapsama sorgularını, sentetik ızgaraları, yüksek hacimli düşük değerli oturumları ve ortak desenli koordineli hesapları arayın." },
    validation: { en: "Replay known extraction strategies at safe scale and verify risk scoring, throttling and investigation evidence.", tr: "Bilinen çıkarma stratejilerini güvenli ölçekte yeniden oynatın; risk puanlama, yavaşlatma ve inceleme kanıtını doğrulayın." },
    limitations: { en: "Aggressive throttling can block legitimate evaluation, research or batch use and cannot stop all imitation.", tr: "Agresif yavaşlatma meşru değerlendirme, araştırma veya toplu kullanımı engelleyebilir ve tüm taklitleri durduramaz." },
    workflow: { en: "Score sessions by coverage and repetition, challenge or throttle elevated risk, preserve privacy-safe evidence and review before account action.", tr: "Oturumları kapsama ve tekrara göre puanlayın, yüksek riski doğrulayın ya da yavaşlatın, gizliliği koruyan kanıt saklayın ve hesap işlemi öncesi inceleyin." },
    sourceIds: ["model-stealing", "nist-aml", "mitre-atlas"],
  },
  {
    id: "membership-inference",
    category: "Data",
    title: { en: "Membership inference and training-data privacy", tr: "Üyelik çıkarımı ve eğitim verisi gizliliği" },
    summary: { en: "Limit what model behavior reveals about whether a record was used.", tr: "Model davranışının bir kaydın kullanılıp kullanılmadığına dair açığa çıkardığı bilgiyi sınırlayın." },
    riskModel: { en: "Confidence patterns or outputs can reveal whether a person's record appeared in training data, creating privacy risk.", tr: "Güven desenleri veya çıktılar bir kişinin kaydının eğitim verisinde bulunup bulunmadığını açığa çıkararak gizlilik riski yaratabilir." },
    prevention: { en: "Minimize sensitive training data, control retention, reduce overfitting, consider privacy-preserving training and restrict detailed scores.", tr: "Hassas eğitim verisini azaltın, saklamayı kontrol edin, aşırı öğrenmeyi düşürün, gizlilik koruyan eğitimi değerlendirin ve ayrıntılı puanları sınırlayın." },
    detection: { en: "Audit privacy leakage on representative subgroups and monitor query patterns that compare closely related records.", tr: "Temsilî alt gruplarda gizlilik sızıntısını denetleyin ve birbirine çok yakın kayıtları karşılaştıran sorgu desenlerini izleyin." },
    validation: { en: "Run membership-inference evaluations against train and holdout records under the same access available to a real caller.", tr: "Üyelik çıkarımı değerlendirmelerini gerçek çağıranın erişimine eş koşullarda eğitim ve ayrılmış kayıtlar üzerinde çalıştırın." },
    limitations: { en: "Privacy tests are attack-model specific, while stronger privacy mechanisms can trade off utility and cost.", tr: "Gizlilik testleri saldırı modeline özeldir; daha güçlü gizlilik mekanizmaları fayda ve maliyetle ödünleşebilir." },
    workflow: { en: "Classify the dataset, remove unnecessary identifiers, train with documented privacy controls, test leakage and block release above threshold.", tr: "Veri setini sınıflandırın, gereksiz tanımlayıcıları kaldırın, belgeli gizlilik kontrolleriyle eğitin, sızıntıyı test edin ve eşik üstünde yayını engelleyin." },
    sourceIds: ["membership-inference", "nist-aml", "nist-genai"],
  },
  {
    id: "adversarial-input-evasion",
    category: "Model",
    title: { en: "Adversarial input and evasion robustness", tr: "Karşıt girdi ve kaçınma dayanıklılığı" },
    summary: { en: "Measure how small input changes alter safety-critical decisions.", tr: "Küçük girdi değişikliklerinin güvenlik açısından kritik kararları nasıl etkilediğini ölçün." },
    riskModel: { en: "Carefully chosen perturbations can move model predictions across decision boundaries while preserving apparent meaning or appearance.", tr: "Özenle seçilmiş bozulmalar görünür anlamı veya görünümü korurken model tahminlerini karar sınırlarının ötesine taşıyabilir." },
    prevention: { en: "Use input constraints, robust training where evidence supports it, ensembles, abstention and downstream safety checks.", tr: "Girdi kısıtları, kanıtın desteklediği yerde dayanıklı eğitim, topluluk modelleri, kaçınma ve alt sistem güvenlik denetimleri kullanın." },
    detection: { en: "Monitor sensitivity to benign transformations, out-of-distribution scores and abrupt confidence shifts across equivalent inputs.", tr: "Zararsız dönüşümlere duyarlılığı, dağılım dışı puanları ve eşdeğer girdilerde ani güven değişimlerini izleyin." },
    validation: { en: "Test realistic perturbation families within the deployment threat model and report worst-case subgroup performance.", tr: "Dağıtım tehdit modeli içindeki gerçekçi bozulma ailelerini test edin ve en kötü alt grup performansını raporlayın." },
    limitations: { en: "Robustness to one perturbation norm or attack family does not transfer automatically to others.", tr: "Bir bozulma normuna veya saldırı ailesine dayanıklılık diğerlerine otomatik olarak aktarılmaz." },
    workflow: { en: "Define valid input transformations, generate bounded tests, compare decision stability, route unstable cases to abstention and retain regressions.", tr: "Geçerli girdi dönüşümlerini tanımlayın, sınırlı testler üretin, karar kararlılığını karşılaştırın, kararsız örnekleri kaçınmaya yönlendirin ve regresyonları saklayın." },
    sourceIds: ["nist-aml", "mitre-atlas", "cisa-deploy"],
  },
  {
    id: "hallucination-risk-model",
    category: "Hallucination",
    title: { en: "Hallucination detection method stack", tr: "Halüsinasyon tespit yöntemleri yığını" },
    summary: { en: "Combine evidence, uncertainty and accountable review instead of trusting one score.", tr: "Tek bir puana güvenmek yerine kanıtı, belirsizliği ve sorumlu incelemeyi birleştirin." },
    riskModel: { en: "A fluent answer can contain unsupported, contradicted, outdated or internally inconsistent claims that users may accept without checking.", tr: "Akıcı bir yanıt kullanıcıların kontrol etmeden kabul edebileceği desteksiz, çelişkili, eski veya kendi içinde tutarsız iddialar içerebilir." },
    prevention: { en: "Limit generation to supported tasks, retrieve approved evidence, require citations, permit abstention and narrow output claims.", tr: "Üretimi destekli görevlerle sınırlayın, onaylı kanıt getirin, kaynak isteyin, yanıt vermemeye izin verin ve çıktı iddialarını daraltın." },
    detection: { en: "Use a layered stack of retrieval support, atomic claims, entailment, sample consistency, semantic uncertainty and human review.", tr: "Bilgi getirme desteği, atomik iddia, çıkarım, örnek tutarlılığı, anlamsal belirsizlik ve insan incelemesinden oluşan katmanlı bir yığın kullanın." },
    validation: { en: "Evaluate each layer and the combined decision policy on representative, time-split and adversarial examples with human labels.", tr: "Her katmanı ve birleşik karar politikasını insan etiketli temsilî, zamana göre ayrılmış ve karşıt örneklerde değerlendirin." },
    limitations: { en: "No method covers every failure class; detectors can share data, model and retrieval errors with the generator.", tr: "Hiçbir yöntem her hata sınıfını kapsamaz; tespit sistemleri üreticiyle aynı veri, model ve bilgi getirme hatalarını paylaşabilir." },
    workflow: { en: "Decompose the answer, retrieve evidence, score support and uncertainty, block high-risk claims, then send unresolved high-impact items to review.", tr: "Yanıtı ayrıştırın, kanıt getirin, destek ve belirsizliği puanlayın, yüksek riskli iddiaları engelleyin ve çözülmeyen yüksek etkili öğeleri incelemeye gönderin." },
    sourceIds: ["nist-genai", "owasp-misinformation", "selfcheckgpt", "semantic-entropy", "factscore"],
    methodComparison: hallucinationMethods,
  },
  {
    id: "retrieval-grounding",
    category: "Hallucination",
    title: { en: "Retrieval grounding and citation alignment", tr: "Bilgi getirme dayanağı ve kaynak uyumu" },
    summary: { en: "Make every material claim traceable to the passage that supports it.", tr: "Her önemli iddiayı onu destekleyen paragrafa kadar izlenebilir kılın." },
    riskModel: { en: "A model can ignore retrieved evidence, cite an irrelevant passage or combine sources into a claim none of them supports.", tr: "Model getirilen kanıtı yok sayabilir, ilgisiz paragraf gösterebilir veya kaynakları hiçbirinin desteklemediği bir iddiada birleştirebilir." },
    prevention: { en: "Retrieve from approved current corpora, preserve passage identifiers, constrain answers to evidence and allow a no-support outcome.", tr: "Onaylı güncel külliyattan bilgi getirin, paragraf kimliklerini koruyun, yanıtı kanıtla sınırlayın ve destek yok sonucuna izin verin." },
    detection: { en: "Score context relevance, claim support and citation coverage separately; flag citations that do not entail the attached claim.", tr: "Bağlam ilgisini, iddia desteğini ve kaynak kapsamını ayrı puanlayın; bağlı iddiayı desteklemeyen kaynakları işaretleyin." },
    validation: { en: "Use answerable and unanswerable queries, stale evidence and distractor passages, then compare automated support labels with reviewers.", tr: "Yanıtlanabilir ve yanıtlanamaz sorgular, eski kanıt ve dikkat dağıtıcı paragraflar kullanın; otomatik destek etiketlerini inceleyenlerle karşılaştırın." },
    limitations: { en: "Grounding cannot rescue a missing, incorrect or poisoned corpus and does not prove the source itself is true.", tr: "Dayanaklandırma eksik, yanlış veya zehirli külliyatı düzeltemez ve kaynağın kendisinin doğru olduğunu kanıtlamaz." },
    workflow: { en: "Classify the question, retrieve current approved passages, answer only supported claims, attach exact citations and abstain when coverage is insufficient.", tr: "Soruyu sınıflandırın, güncel onaylı paragrafları getirin, yalnız destekli iddiaları yanıtlayın, kesin kaynak ekleyin ve kapsam yetersizse yanıt vermeyin." },
    sourceIds: ["rag-paper", "factscore", "nist-genai"],
  },
  {
    id: "atomic-claim-verification",
    category: "Hallucination",
    title: { en: "Atomic claim decomposition", tr: "Atomik iddia ayrıştırma" },
    summary: { en: "Break long prose into claims that can each be checked.", tr: "Uzun metni ayrı ayrı kontrol edilebilir iddialara bölün." },
    riskModel: { en: "Document-level scores hide mixed outputs where several accurate statements surround one unsupported high-impact claim.", tr: "Belge düzeyindeki puanlar, birkaç doğru ifadenin desteklenmeyen yüksek etkili bir iddiayı çevrelediği karma çıktıları gizler." },
    prevention: { en: "Ask for bounded claims and structured fields, separate facts from interpretation and require evidence identifiers for factual fields.", tr: "Sınırlı iddialar ve yapılandırılmış alanlar isteyin, olguyu yorumdan ayırın ve olgusal alanlarda kanıt kimliği şart koşun." },
    detection: { en: "Decompose sentences into independently verifiable units and label each supported, contradicted, unsupported or undecidable.", tr: "Cümleleri bağımsız doğrulanabilir birimlere ayırın ve her birini destekli, çelişkili, desteksiz veya belirsiz olarak etiketleyin." },
    validation: { en: "Measure decomposition completeness and claim labels against dual human annotation, especially for numbers, dates and negation.", tr: "Özellikle sayı, tarih ve olumsuzluklarda ayrıştırma tamlığını ve iddia etiketlerini çift insan etiketiyle ölçün." },
    limitations: { en: "Decomposition can remove context, split claims incorrectly or create units whose truth depends on unstated assumptions.", tr: "Ayrıştırma bağlamı kaldırabilir, iddiaları yanlış bölebilir veya doğruluğu söylenmeyen varsayımlara bağlı birimler oluşturabilir." },
    workflow: { en: "Extract claims, preserve sentence context, retrieve evidence per claim, adjudicate labels and block the document if critical support is missing.", tr: "İddiaları çıkarın, cümle bağlamını koruyun, iddia başına kanıt getirin, etiketleri karara bağlayın ve kritik destek eksikse belgeyi engelleyin." },
    sourceIds: ["factscore", "halueval", "truthfulqa"],
  },
  {
    id: "nli-entailment-checking",
    category: "Hallucination",
    title: { en: "Entailment-based evidence checking", tr: "Çıkarım tabanlı kanıt denetimi" },
    summary: { en: "Distinguish support from contradiction and missing evidence.", tr: "Desteği, çelişkiyi ve eksik kanıtı birbirinden ayırın." },
    riskModel: { en: "Keyword overlap can make a citation appear relevant even when it contradicts or fails to establish the generated claim.", tr: "Anahtar kelime örtüşmesi, bir kaynağı üretilen iddiayla çelişse veya onu kanıtlamasa bile ilgili gösterebilir." },
    prevention: { en: "Keep evidence passages short and attributable, normalize dates and units and require undecidable as an explicit outcome.", tr: "Kanıt paragraflarını kısa ve atfedilebilir tutun, tarih ve birimleri normalleştirin, belirsiz sonucu açık seçenek yapın." },
    detection: { en: "Run natural-language inference for each claim-passage pair and aggregate conservatively across independent sources.", tr: "Her iddia-paragraf çifti için doğal dil çıkarımı çalıştırın ve bağımsız kaynaklar üzerinde ihtiyatlı biçimde birleştirin." },
    validation: { en: "Evaluate domain, language, numerical, temporal and negation slices; calibrate thresholds against human adjudication.", tr: "Alan, dil, sayısal, zamansal ve olumsuzluk dilimlerini değerlendirin; eşikleri insan kararına göre kalibre edin." },
    limitations: { en: "NLI models inherit training-domain limits and may treat lexical similarity as evidence.", tr: "NLI modelleri eğitim alanı sınırlarını devralır ve sözcük benzerliğini kanıt sanabilir." },
    workflow: { en: "Pair each atomic claim with its cited passage, classify support, keep undecidable separate and escalate contradictions immediately.", tr: "Her atomik iddiayı kaynak paragrafıyla eşleyin, desteği sınıflandırın, belirsizi ayrı tutun ve çelişkileri hemen yükseltin." },
    sourceIds: ["halueval", "factscore", "selfcheckgpt"],
  },
  {
    id: "self-consistency-uncertainty",
    category: "Hallucination",
    title: { en: "Self-consistency and semantic uncertainty", tr: "Öz tutarlılık ve anlamsal belirsizlik" },
    summary: { en: "Use answer variation to find confabulation risk, not to vote truth into existence.", tr: "Yanıt değişimini doğruluğu oylamak için değil, uydurma riskini bulmak için kullanın." },
    riskModel: { en: "When the model lacks stable knowledge, repeated generations can express incompatible meanings while each sounds confident.", tr: "Model kararlı bilgiden yoksunken tekrarlanan üretimler, her biri kendinden emin görünse de uyumsuz anlamlar ifade edebilir." },
    prevention: { en: "Allow abstention, retrieve evidence before generation and keep high-uncertainty tasks outside automated decision paths.", tr: "Yanıt vermemeye izin verin, üretimden önce kanıt getirin ve yüksek belirsizlikli görevleri otomatik karar yollarının dışında tutun." },
    detection: { en: "Sample multiple answers, cluster semantic equivalents and measure disagreement with SelfCheckGPT-style or semantic-entropy signals.", tr: "Birden çok yanıt örnekleyin, anlamsal eşdeğerleri kümeleyin ve SelfCheckGPT tarzı ya da anlamsal entropi sinyalleriyle uyuşmazlığı ölçün." },
    validation: { en: "Calibrate on in-domain factual labels and test systematic falsehoods separately because consistent error can look certain.", tr: "Alan içi olgusal etiketlerde kalibre edin ve tutarlı hata kesin görünebildiği için sistematik yanlışları ayrı test edin." },
    limitations: { en: "Sampling is costly, semantic clustering can be wrong and low uncertainty does not establish factuality.", tr: "Örnekleme maliyetlidir, anlamsal kümeleme yanlış olabilir ve düşük belirsizlik doğruluğu kanıtlamaz." },
    workflow: { en: "Generate controlled samples, normalize meanings, compute disagreement, combine with evidence support and refuse or review above threshold.", tr: "Kontrollü örnekler üretin, anlamları normalleştirin, uyuşmazlığı hesaplayın, kanıt desteğiyle birleştirin ve eşik üstünde reddedin ya da inceleyin." },
    sourceIds: ["selfcheckgpt", "semantic-entropy", "truthfulqa"],
  },
  {
    id: "hallucination-evaluation-sets",
    category: "Hallucination",
    title: { en: "Hallucination evaluation sets and drift", tr: "Halüsinasyon değerlendirme setleri ve kayma" },
    summary: { en: "Measure the failures your product sees, then keep the test set moving with reality.", tr: "Ürününüzün gördüğü hataları ölçün ve test setini gerçeklikle birlikte güncel tutun." },
    riskModel: { en: "Generic benchmarks can hide domain, language, time and workflow failures that dominate a real deployment.", tr: "Genel ölçütler gerçek dağıtımda baskın olan alan, dil, zaman ve iş akışı hatalarını gizleyebilir." },
    prevention: { en: "Create representative test strata, preserve fresh holdouts, document label policy and prevent evaluation examples from entering training.", tr: "Temsilî test katmanları oluşturun, taze ayrılmış örnekleri koruyun, etiket politikasını belgeleyin ve değerlendirme örneklerinin eğitime girmesini önleyin." },
    detection: { en: "Track factual precision, unsupported-claim rate, abstention, citation coverage and severity by domain, language and model version.", tr: "Olgusal kesinliği, desteksiz iddia oranını, yanıt vermemeyi, kaynak kapsamını ve ciddiyeti alan, dil ve model sürümüne göre izleyin." },
    validation: { en: "Use blinded dual review, adjudicate disagreement, report confidence intervals and rerun time-split holdouts after releases.", tr: "Kör çift inceleme kullanın, uyuşmazlığı karara bağlayın, güven aralıklarını raporlayın ve sürümlerden sonra zamana göre ayrılmış setleri yeniden çalıştırın." },
    limitations: { en: "Benchmarks become stale, can be contaminated and rarely predict every live failure mode.", tr: "Ölçütler eskir, kirlenebilir ve canlıdaki her hata biçimini nadiren öngörür." },
    workflow: { en: "Sample production-shaped prompts without personal data, label with evidence, freeze a release gate, monitor drift and refresh only with versioned review.", tr: "Kişisel veri olmadan üretim biçimli promptlar örnekleyin, kanıtla etiketleyin, sürüm kapısını dondurun, kaymayı izleyin ve yalnız sürümlü incelemeyle yenileyin." },
    sourceIds: ["halueval", "truthfulqa", "factscore", "nist-genai"],
  },
  {
    id: "human-review-calibrated-abstention",
    category: "Hallucination",
    title: { en: "Human review and calibrated abstention", tr: "İnsan incelemesi ve kalibre edilmiş kaçınma" },
    summary: { en: "Define when the system stops and who owns the unresolved claim.", tr: "Sistemin ne zaman duracağını ve çözülmeyen iddiadan kimin sorumlu olduğunu tanımlayın." },
    riskModel: { en: "Automated checks can pass plausible errors, while unstructured review can become inconsistent, slow or overly trusting of fluent text.", tr: "Otomatik denetimler makul görünen hataları geçirebilir; yapılandırılmamış inceleme tutarsız, yavaş veya akıcı metne fazla güvenen hale gelebilir." },
    prevention: { en: "Set risk tiers, evidence requirements, reviewer qualifications, service levels and a safe abstention response before launch.", tr: "Yayın öncesi risk katmanlarını, kanıt gereksinimlerini, inceleyen yeterliliğini, hizmet sürelerini ve güvenli kaçınma yanıtını belirleyin." },
    detection: { en: "Route cases using claim severity, missing support, contradiction, uncertainty and detector disagreement rather than model confidence alone.", tr: "Örnekleri yalnız model güvenine göre değil, iddia ciddiyeti, eksik destek, çelişki, belirsizlik ve tespit uyuşmazlığına göre yönlendirin." },
    validation: { en: "Measure reviewer agreement, correction rate, queue delay, anchoring and outcomes after release; audit a random sample of passes.", tr: "İnceleyen uyumunu, düzeltme oranını, kuyruk gecikmesini, bağlanmayı ve yayın sonrası sonuçları ölçün; geçenlerin rastgele örneğini denetleyin." },
    limitations: { en: "Human review does not guarantee truth and can fail under overload, weak evidence or ambiguous accountability.", tr: "İnsan incelemesi doğruluğu garanti etmez; aşırı yük, zayıf kanıt veya belirsiz sorumluluk altında başarısız olabilir." },
    workflow: { en: "Apply automated gates, abstain on critical uncertainty, present claims beside evidence, record reviewer decisions and feed confirmed errors into regression tests.", tr: "Otomatik kapıları uygulayın, kritik belirsizlikte yanıt vermeyin, iddiaları kanıt yanında gösterin, inceleyen kararını kaydedin ve doğrulanmış hataları regresyon testlerine ekleyin." },
    sourceIds: ["nist-genai", "factscore", "semantic-entropy", "halueval"],
  },
];

export const sourceById = new Map(securitySources.map((source) => [source.id, source]));

export function localize(value: LocalizedText, locale: "en" | "tr") {
  return value[locale];
}
